# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d9a6ff27c1e6ed128c0ad5c80fba34c10842294e15c34844063d25507b447ed911eebd0fb6a5b8f758ae74fd09b5250be84b678bc509f64ec359404e922c6fab

test:
  secret_key_base: 593a37a7cc9f1f16997994aec637a2188732d0f896c9ea3283efc057313567c24e199507b7fcfc9b072d616146c8c6b24b4110801e3d48b5739b8c031ad39121

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
